An SQL directory was created in resources with tables.sql file inside…
JohnOldman2018/rooms_manager pull request #8
Opened 2021-09-14 17:56 UTC by JohnOldman2018

…, SQL scripts were written into the file

2021-09-14 20:42 UTC, amussagaliyev requested changes
Let's use snake_case instead of camelCase.
Lower case for non reserved words like column and table names.

2021-09-14 20:42 UTC, amussagaliyev commented on src/main/resources/SQL/tables.sql
> +    CountryCode CHARACTER (2) PRIMARY KEY,
What is the difference between character and varchar data types in MySQL?
Why did you choose CHARACTER?

2021-09-14 20:42 UTC, amussagaliyev commented on src/main/resources/SQL/tables.sql
> +	Country CHARACTER (150) NOT NULL,
let's call it country_code and make length 2

2021-09-14 20:42 UTC, amussagaliyev commented on src/main/resources/SQL/tables.sql
> +    LightOn BIT DEFAULT 0 NOT NULL
let's call it light_is_on

2021-09-14 20:42 UTC, amussagaliyev commented on src/main/resources/SQL/tables.sql
> +    RoomID INTEGER (2) PRIMARY KEY NOT NULL AUTO_INCREMENT,
Why is RoomID has length 2? Is it onliy for 99 values? What about 100, 1000 etc?

2021-09-14 20:42 UTC, amussagaliyev commented on src/main/resources/SQL/tables.sql
> +    CountryCode CHARACTER (2) PRIMARY KEY,
lets call it just `code` and `name`

2021-09-15 03:48 UTC, JohnOldman2018 commented on src/main/resources/SQL/tables.sql
> +    CountryCode CHARACTER (2) PRIMARY KEY,
That was my first choice of  the variable name. Later I made a little research and found out that VARCHAR is more preferable for our task because it is less consumptive than CHARACTER type. VARCHAR takes space only enough for the number of its characters, it acts the same as the CHARACTER VARIABLE notion. On the other hand, the CHARACTER type takes all the space indicated by the programmer in parentheses.
I didn't make the correction because I awaited more corrections on other issues in my code.

2021-09-15 03:51 UTC, JohnOldman2018 commented on src/main/resources/SQL/tables.sql
> +	Country CHARACTER (150) NOT NULL,
Yes, that'll be more descriptive in the Rooms context.

2021-09-15 03:51 UTC, JohnOldman2018 commented on src/main/resources/SQL/tables.sql
> +    LightOn BIT DEFAULT 0 NOT NULL
Yes, that'll be more descriptive

2021-09-15 03:52 UTC, JohnOldman2018 commented on src/main/resources/SQL/tables.sql
> +    RoomID INTEGER (2) PRIMARY KEY NOT NULL AUTO_INCREMENT,
That was my copy-past mistake.

2021-09-15 03:59 UTC, JohnOldman2018 reviewed
I've made all the required changes and will commit it in no time.

2021-09-15 03:59 UTC, JohnOldman2018 commented on src/main/resources/SQL/tables.sql
> +    CountryCode CHARACTER (2) PRIMARY KEY,
And as I think VARCHAR is more preferable to CHARACTER VARIABLE, because it is less wordy and more recognizible by the programmer community.

2021-09-15 04:23 UTC, merged